
package com.fbol.ucic.service.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "XPIpAnlytcsMktDtlPrflService", targetNamespace = "XPIpAnlytcsMktDtlProfile", wsdlLocation = "file:/C:/Users/okekenf01/source/repos/fbol-ucic-service/src/main/resources/interfaces/XPIpAnlytcsMktDtlProfile_v1_0.wsdl")
public class XPIpAnlytcsMktDtlPrflService
    extends Service
{

    private final static URL XPIPANLYTCSMKTDTLPRFLSERVICE_WSDL_LOCATION;
    private final static WebServiceException XPIPANLYTCSMKTDTLPRFLSERVICE_EXCEPTION;
    private final static QName XPIPANLYTCSMKTDTLPRFLSERVICE_QNAME = new QName("XPIpAnlytcsMktDtlProfile", "XPIpAnlytcsMktDtlPrflService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/okekenf01/source/repos/fbol-ucic-service/src/main/resources/interfaces/XPIpAnlytcsMktDtlProfile_v1_0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XPIPANLYTCSMKTDTLPRFLSERVICE_WSDL_LOCATION = url;
        XPIPANLYTCSMKTDTLPRFLSERVICE_EXCEPTION = e;
    }

    public XPIpAnlytcsMktDtlPrflService() {
        super(__getWsdlLocation(), XPIPANLYTCSMKTDTLPRFLSERVICE_QNAME);
    }

    public XPIpAnlytcsMktDtlPrflService(WebServiceFeature... features) {
        super(__getWsdlLocation(), XPIPANLYTCSMKTDTLPRFLSERVICE_QNAME, features);
    }

    public XPIpAnlytcsMktDtlPrflService(URL wsdlLocation) {
        super(wsdlLocation, XPIPANLYTCSMKTDTLPRFLSERVICE_QNAME);
    }

    public XPIpAnlytcsMktDtlPrflService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XPIPANLYTCSMKTDTLPRFLSERVICE_QNAME, features);
    }

    public XPIpAnlytcsMktDtlPrflService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XPIpAnlytcsMktDtlPrflService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns XPIpAnlytcsMktDtlProfile
     */
    @WebEndpoint(name = "XPIpAnlytcsMktDtlProfilePort")
    public XPIpAnlytcsMktDtlProfile getXPIpAnlytcsMktDtlProfilePort() {
        return super.getPort(new QName("XPIpAnlytcsMktDtlProfile", "XPIpAnlytcsMktDtlProfilePort"), XPIpAnlytcsMktDtlProfile.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XPIpAnlytcsMktDtlProfile
     */
    @WebEndpoint(name = "XPIpAnlytcsMktDtlProfilePort")
    public XPIpAnlytcsMktDtlProfile getXPIpAnlytcsMktDtlProfilePort(WebServiceFeature... features) {
        return super.getPort(new QName("XPIpAnlytcsMktDtlProfile", "XPIpAnlytcsMktDtlProfilePort"), XPIpAnlytcsMktDtlProfile.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XPIPANLYTCSMKTDTLPRFLSERVICE_EXCEPTION!= null) {
            throw XPIPANLYTCSMKTDTLPRFLSERVICE_EXCEPTION;
        }
        return XPIPANLYTCSMKTDTLPRFLSERVICE_WSDL_LOCATION;
    }

}
