
package com.fbol.ucic.service.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "XPIpAnlytcsMktDtlProfile", targetNamespace = "XPIpAnlytcsMktDtlProfile")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface XPIpAnlytcsMktDtlProfile {


    /**
     * 
     * @param xpRetrieveIpAnlytcsMktDtlRqst
     * @return
     *     returns com.fbol.ucic.service.wsdl.XPRetrieveIpAnlytcsMktDtlRsp
     */
    @WebMethod(operationName = "XPRetrieveIpAnalyticsMarketingDetail", action = "XPIpAnlytcsMktDtlProfileXPRetrieveIpAnalyticsMarketingDetail/")
    @WebResult(name = "XPRtrvIpAnlytcsMktDtlRsp", targetNamespace = "XPRetrieveIpAnlytcsMktDtlRsp", partName = "XPRetrieveIpAnlytcsMktDtlRsp")
    public XPRetrieveIpAnlytcsMktDtlRsp xpRetrieveIpAnalyticsMarketingDetail(
        @WebParam(name = "XPRtrvIpAnlytcsMktDtlRqst", targetNamespace = "XPRetrieveIpAnlytcsMktDtlRqst", partName = "XPRetrieveIpAnlytcsMktDtlRqst")
        XPRetrieveIpAnlytcsMktDtlRqst xpRetrieveIpAnlytcsMktDtlRqst);

}
