/****** Object:  Table [dbo].[STGkeys]    Script Date: 9/19/2022 5:20:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[STGkeys](
	[TNAME] [varchar](100) NOT NULL,
	[TKEYS] [varchar](200) NULL,
	[INCLUDEDCOLS] [varchar](max) NULL,
 CONSTRAINT [PK_STGkeys_TNAME] PRIMARY KEY CLUSTERED 
(
	[TNAME] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


