apiVersion : apps/v1
kind: Deployment
metadata:
  name: fbolbackbasexaabatch
  namespace: fbtestfinite01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fbolbackbasexaabatch
  template:
    metadata:
      labels:
        app: fbolbackbasexaabatch
    spec:
      containers:
        - name: fbolbackbasexaabatch
          image: fbcusbbtestcr01.azurecr.io/fbolbackbasexaabatch
          ports:
            - containerPort: 9085
          env:
            - name: MAIN_CLASS
              value: com.fbol.xaabatch.Xaabatchapplication
            # Azure KeyVault Secrets
            - name: SQL_URL
              valueFrom:
                secretKeyRef:
                  name: fisxaa-secrets       # k8s secret name. This is auto synced during creation and deletion of the POD
                  key: XaaUrl            # This must match the kv configuration in the yaml under secretObjects
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: fisxaa-secrets
                  key: XaaSqlUser
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fisxaa-secrets
                  key: XaaSqlPassword
            - name: AZURE_STORAGE_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: fisxaa-secrets
                  key: XaaStorageUrl
            - name: CODE_CONNECT_CONN_STRING
              value: ""
          volumeMounts:
            - name: secrets-volume
              mountPath: "/mnt/secrets"
              readOnly: true
      volumes:
        - name: secrets-volume                        # The volume created by Kubernetes secret store csi driver. This block makes it available to the pod for mounting
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-keyvault-user-msi

---

# This is a SecretProviderClass example using user-assigned identity to access Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-user-msi                                       # General name for k8s resource name
  namespace: fbtestfinite01
spec:
  provider: azure                                                     # Name of the provider
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                                      # Specify access mode to enable use of User-assigned managed identity. Default is "false"
    userAssignedIdentityID: "a64c52e3-83ea-40e8-801d-70f29b9efe09"    # The user assigned identity ID is required for User-assigned Managed Identity mode
    tenantId: "360cbd8d-d8bd-4a8d-ba4a-2e358864c62a"                  # The tenant ID of the keyVault
    keyvaultName: "fb-cus-bb-test-kv-01"                             # The name of KeyVault
    cloudName: ""
    # List of secrets to pull from the key vault
    objects: |
      array:
          - |
              objectName: XaaUrl
              objectType: secret
          - |
              objectName: XaaSqlUser
              objectType: secret
          - |
              objectName: XaaSqlPassword
              objectType: secret
          - |
              objectName: XaaStorageUrl
              objectType: secret
  secretObjects:                                      # The Kubernetes secret to create. SecretObject defines the desired state of synced K8s secret objects
    - secretName: fisxaa-secrets              # Name of the Kubernetes secret object
      type: Opaque
      data:
        - key: XaaUrl                      # A key name inside the new secret. Data field to populate. This must match in deployment yaml for key
          objectName: XaaUrl               # Secret value to use. Name of the mounted content to sync, such as object name or object alias
        - key: XaaSqlUser
          objectName: XaaSqlUser
        - key: XaaSqlPassword
          objectName: XaaSqlPassword
        - key: XaaStorageUrl
          objectName: XaaStorageUrl