apiVersion : apps/v1
kind: Deployment
metadata:
  name: fbolbackbaseucicservice
  namespace: fbdevfinite01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fbolbackbaseucicservice
  template:
    metadata:
      labels:
        app: fbolbackbaseucicservice
    spec:
      containers:
        - name: fbolbackbaseucicservice
          image: fbcusbbdevcr01.azurecr.io/fbolbackbaseucicservice
          ports:
            - containerPort: 9085
          env:
            - name: MAIN_CLASS
              value: com.fbol.ucic.service.FbolUcicServiceApplication
            # Azure KeyVault Secrets
            - name: UNAME
              valueFrom:
                secretKeyRef:
                  name: fissegmint-secrets       # k8s secret name. This is auto synced during creation and deletion of the POD
                  key: SegmintUname            # This must match the kv configuration in the yaml under secretObjects
            - name: BANKID
              value: "840"
            - name: SRCID
              value: "firstbank"
            - name: FIS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: fissegmint-secrets
                  key: SegmintFisEndpoint
            - name: LOGGING_LEVEL
              value: "DEBUG"
          volumeMounts:
            - name: secrets-volume
              mountPath: "/mnt/secrets"
              readOnly: true
      volumes:
        - name: secrets-volume                        # The volume created by Kubernetes secret store csi driver. This block makes it available to the pod for mounting
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-keyvault-user-msi

---

# This is a SecretProviderClass example using user-assigned identity to access Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-user-msi                                       # General name for k8s resource name
  namespace: fbdevfinite01
spec:
  provider: azure                                                     # Name of the provider
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                                      # Specify access mode to enable use of User-assigned managed identity. Default is "false"
    userAssignedIdentityID: "3adf07c9-fe56-4249-a0d5-4ecb25a5ca34"    # The user assigned identity ID is required for User-assigned Managed Identity mode
    tenantId: "360cbd8d-d8bd-4a8d-ba4a-2e358864c62a"                  # The tenant ID of the keyVault
    keyvaultName: "fb-cus-bb-dev-kv-03"                               # The name of KeyVault
    cloudName: ""
    # List of secrets to pull from the key vault
    objects: |
      array:
          - |
              objectName: SegmintUname
              objectType: secret
          - |
              objectName: SegmintFisEndpoint
              objectType: secret
  secretObjects:                                      # The Kubernetes secret to create. SecretObject defines the desired state of synced K8s secret objects
    - secretName: fissegmint-secrets              # Name of the Kubernetes secret object
      type: Opaque
      data:
        - key: SegmintUname                      # A key name inside the new secret. Data field to populate. This must match in deployment yaml for key
          objectName: SegmintUname               # Secret value to use. Name of the mounted content to sync, such as object name or object alias
        - key: SegmintFisEndpoint
          objectName: SegmintFisEndpoint