
package com.fbol.ucic.service.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * This is an ordered list of messages that occurred in the
 * 						service. The first message in the list was generated by the
 * 						client-facing service. Any subsequent messages were generated by
 * 						any subsystem service(s).
 * 
 * <p>Java class for tMsgLst complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tMsgLst"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Msg" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="MsgCde" type="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;element name="Typ" type="{FisCommonRspHdr}tMsgType"&gt;
 *                   &lt;element name="DataLnkId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"&gt;
 *                   &lt;element name="MsgLcl" type="{FisCommonRspHdr}tLocale" minOccurs="0"&gt;
 *                   &lt;element name="Txt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"&gt;
 *                   &lt;element name="PrmtrLst" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Prmtr" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="SpcfrId" type="{FisCommonRspHdr}tSpcfrId"&gt;
 *                                       &lt;element name="PrmtrTyp" type="{FisCommonRspHdr}tPrmtrTyp"&gt;
 *                                       &lt;element name="Cde" type="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                       &lt;element name="ValCde" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"&gt;
 *                                       &lt;element name="Val" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tMsgLst", namespace = "https://www.firstbankonline.com/FisCommonRspHdr", propOrder = {
    "msg"
})
public class TMsgLst {

    @XmlElement(name = "Msg", required = true)
    protected List<TMsgLst.Msg> msg;

    /**
     * Gets the value of the msg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the msg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMsg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TMsgLst.Msg }
     * 
     * 
     */
    public List<TMsgLst.Msg> getMsg() {
        if (msg == null) {
            msg = new ArrayList<TMsgLst.Msg>();
        }
        return this.msg;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="MsgCde" type="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *         &lt;element name="Typ" type="{FisCommonRspHdr}tMsgType"&gt;
     *         &lt;element name="DataLnkId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"&gt;
     *         &lt;element name="MsgLcl" type="{FisCommonRspHdr}tLocale" minOccurs="0"&gt;
     *         &lt;element name="Txt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"&gt;
     *         &lt;element name="PrmtrLst" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Prmtr" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="SpcfrId" type="{FisCommonRspHdr}tSpcfrId"&gt;
     *                             &lt;element name="PrmtrTyp" type="{FisCommonRspHdr}tPrmtrTyp"&gt;
     *                             &lt;element name="Cde" type="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                             &lt;element name="ValCde" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"&gt;
     *                             &lt;element name="Val" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "msgCde",
        "typ",
        "dataLnkId",
        "msgLcl",
        "txt",
        "prmtrLst"
    })
    public static class Msg {

        @XmlElement(name = "MsgCde", namespace = "https://www.firstbankonline.com/FisCommonRspHdr", required = true)
        protected String msgCde;
        @XmlElement(name = "Typ", namespace = "https://www.firstbankonline.com/FisCommonRspHdr", required = true)
        @XmlSchemaType(name = "string")
        protected TMsgType typ;
        @XmlElement(name = "DataLnkId", namespace = "https://www.firstbankonline.com/FisCommonRspHdr")
        protected String dataLnkId;
        @XmlElement(name = "MsgLcl", namespace = "https://www.firstbankonline.com/FisCommonRspHdr")
        protected String msgLcl;
        @XmlElement(name = "Txt", namespace = "https://www.firstbankonline.com/FisCommonRspHdr")
        protected String txt;
        @XmlElement(name = "PrmtrLst", namespace = "https://www.firstbankonline.com/FisCommonRspHdr")
        protected TMsgLst.Msg.PrmtrLst prmtrLst;

        /**
         * Gets the value of the msgCde property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMsgCde() {
            return msgCde;
        }

        /**
         * Sets the value of the msgCde property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMsgCde(String value) {
            this.msgCde = value;
        }

        /**
         * Gets the value of the typ property.
         * 
         * @return
         *     possible object is
         *     {@link TMsgType }
         *     
         */
        public TMsgType getTyp() {
            return typ;
        }

        /**
         * Sets the value of the typ property.
         * 
         * @param value
         *     allowed object is
         *     {@link TMsgType }
         *     
         */
        public void setTyp(TMsgType value) {
            this.typ = value;
        }

        /**
         * Gets the value of the dataLnkId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDataLnkId() {
            return dataLnkId;
        }

        /**
         * Sets the value of the dataLnkId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataLnkId(String value) {
            this.dataLnkId = value;
        }

        /**
         * Gets the value of the msgLcl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMsgLcl() {
            return msgLcl;
        }

        /**
         * Sets the value of the msgLcl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMsgLcl(String value) {
            this.msgLcl = value;
        }

        /**
         * Gets the value of the txt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTxt() {
            return txt;
        }

        /**
         * Sets the value of the txt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTxt(String value) {
            this.txt = value;
        }

        /**
         * Gets the value of the prmtrLst property.
         * 
         * @return
         *     possible object is
         *     {@link TMsgLst.Msg.PrmtrLst }
         *     
         */
        public TMsgLst.Msg.PrmtrLst getPrmtrLst() {
            return prmtrLst;
        }

        /**
         * Sets the value of the prmtrLst property.
         * 
         * @param value
         *     allowed object is
         *     {@link TMsgLst.Msg.PrmtrLst }
         *     
         */
        public void setPrmtrLst(TMsgLst.Msg.PrmtrLst value) {
            this.prmtrLst = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Prmtr" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="SpcfrId" type="{FisCommonRspHdr}tSpcfrId"&gt;
         *                   &lt;element name="PrmtrTyp" type="{FisCommonRspHdr}tPrmtrTyp"&gt;
         *                   &lt;element name="Cde" type="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *                   &lt;element name="ValCde" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"&gt;
         *                   &lt;element name="Val" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "prmtr"
        })
        public static class PrmtrLst {

            @XmlElement(name = "Prmtr", namespace = "https://www.firstbankonline.com/FisCommonRspHdr", required = true)
            protected List<TMsgLst.Msg.PrmtrLst.Prmtr> prmtr;

            /**
             * Gets the value of the prmtr property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the prmtr property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPrmtr().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TMsgLst.Msg.PrmtrLst.Prmtr }
             * 
             * 
             */
            public List<TMsgLst.Msg.PrmtrLst.Prmtr> getPrmtr() {
                if (prmtr == null) {
                    prmtr = new ArrayList<TMsgLst.Msg.PrmtrLst.Prmtr>();
                }
                return this.prmtr;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="SpcfrId" type="{FisCommonRspHdr}tSpcfrId"&gt;
             *         &lt;element name="PrmtrTyp" type="{FisCommonRspHdr}tPrmtrTyp"&gt;
             *         &lt;element name="Cde" type="{http://www.w3.org/2001/XMLSchema}string"&gt;
             *         &lt;element name="ValCde" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"&gt;
             *         &lt;element name="Val" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "spcfrId",
                "prmtrTyp",
                "cde",
                "valCde",
                "val"
            })
            public static class Prmtr {

                @XmlElement(name = "SpcfrId", namespace = "https://www.firstbankonline.com/FisCommonRspHdr")
                protected int spcfrId;
                @XmlElement(name = "PrmtrTyp", namespace = "https://www.firstbankonline.com/FisCommonRspHdr", required = true)
                @XmlSchemaType(name = "string")
                protected TPrmtrTyp prmtrTyp;
                @XmlElement(name = "Cde", namespace = "https://www.firstbankonline.com/FisCommonRspHdr", required = true)
                protected String cde;
                @XmlElement(name = "ValCde", namespace = "https://www.firstbankonline.com/FisCommonRspHdr")
                protected String valCde;
                @XmlElement(name = "Val", namespace = "https://www.firstbankonline.com/FisCommonRspHdr")
                protected String val;

                /**
                 * Gets the value of the spcfrId property.
                 * 
                 */
                public int getSpcfrId() {
                    return spcfrId;
                }

                /**
                 * Sets the value of the spcfrId property.
                 * 
                 */
                public void setSpcfrId(int value) {
                    this.spcfrId = value;
                }

                /**
                 * Gets the value of the prmtrTyp property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TPrmtrTyp }
                 *     
                 */
                public TPrmtrTyp getPrmtrTyp() {
                    return prmtrTyp;
                }

                /**
                 * Sets the value of the prmtrTyp property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TPrmtrTyp }
                 *     
                 */
                public void setPrmtrTyp(TPrmtrTyp value) {
                    this.prmtrTyp = value;
                }

                /**
                 * Gets the value of the cde property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCde() {
                    return cde;
                }

                /**
                 * Sets the value of the cde property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCde(String value) {
                    this.cde = value;
                }

                /**
                 * Gets the value of the valCde property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValCde() {
                    return valCde;
                }

                /**
                 * Sets the value of the valCde property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValCde(String value) {
                    this.valCde = value;
                }

                /**
                 * Gets the value of the val property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVal() {
                    return val;
                }

                /**
                 * Sets the value of the val property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVal(String value) {
                    this.val = value;
                }

            }

        }

    }

}
