
package com.fbol.ssoremit.service.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RemittanceManagerSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RemittanceManagerSoap {


    /**
     * 
     * @param xmlRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Execute", action = "http://tempuri.org/Execute")
    @WebResult(name = "ExecuteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Execute", targetNamespace = "http://tempuri.org/", className = "com.fbol.ssoremit.service.wsdl.Execute")
    @ResponseWrapper(localName = "ExecuteResponse", targetNamespace = "http://tempuri.org/", className = "com.fbol.ssoremit.service.wsdl.ExecuteResponse")
    public String execute(
        @WebParam(name = "xmlRequest", targetNamespace = "http://tempuri.org/")
        String xmlRequest);

}
