
package com.fbol.ssoremit.service.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RemittanceManager", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://test-portal.remitstreamreceivables.com/API/RemittanceManager/RemittanceManager.asmx?WSDL")
public class RemittanceManager
    extends Service
{

    private final static URL REMITTANCEMANAGER_WSDL_LOCATION;
    private final static WebServiceException REMITTANCEMANAGER_EXCEPTION;
    private final static QName REMITTANCEMANAGER_QNAME = new QName("http://tempuri.org/", "RemittanceManager");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://test-portal.remitstreamreceivables.com/API/RemittanceManager/RemittanceManager.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REMITTANCEMANAGER_WSDL_LOCATION = url;
        REMITTANCEMANAGER_EXCEPTION = e;
    }

    public RemittanceManager() {
        super(__getWsdlLocation(), REMITTANCEMANAGER_QNAME);
    }

    public RemittanceManager(WebServiceFeature... features) {
        super(__getWsdlLocation(), REMITTANCEMANAGER_QNAME, features);
    }

    public RemittanceManager(URL wsdlLocation) {
        super(wsdlLocation, REMITTANCEMANAGER_QNAME);
    }

    public RemittanceManager(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REMITTANCEMANAGER_QNAME, features);
    }

    public RemittanceManager(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RemittanceManager(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RemittanceManagerSoap
     */
    @WebEndpoint(name = "RemittanceManagerSoap")
    public RemittanceManagerSoap getRemittanceManagerSoap() {
        return super.getPort(new QName("http://tempuri.org/", "RemittanceManagerSoap"), RemittanceManagerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RemittanceManagerSoap
     */
    @WebEndpoint(name = "RemittanceManagerSoap")
    public RemittanceManagerSoap getRemittanceManagerSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "RemittanceManagerSoap"), RemittanceManagerSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REMITTANCEMANAGER_EXCEPTION!= null) {
            throw REMITTANCEMANAGER_EXCEPTION;
        }
        return REMITTANCEMANAGER_WSDL_LOCATION;
    }

}
